### ISSUE TITLE
Step 2: compute NBBO for selected securities

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/dlab-finance#8]
NBBO = Nationwide Best Buy Offer

The idea is very similar to the functionality provided by pandas' [fillna](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.fillna.html).

The idea is to construct a timeseries indexed data frame, with a column for each exchange. For each second, compute the lowest price available for each exchange. If a price is missing, it should be filled forward from the previous available timepoint.

cc @rsoni1

**Comment by davclark** [comment]
@nitalpatwa and I were talking, and I'm not clear now if we should be grabbing the lowest price from the trade file or from the quote file. Sorry - my notes are not grea!

**Comment by rsoni1** [comment]
NBBO calculation for a single day file for all securities is now checked in. The spark job with 4 nodes takes 7 mins to complete and generates NBBO as a timeseries for all securities. https://github.com/berkeley-dsc/dlab-finance/tree/master/nbbo

The job can be further optimized by using compression for read files once Issue https://github.com/berkeley-dsc/dlab-finance/issues/5 is resolved.

Further data partition and shuffle analysis can be conducted to optimize configuration parameters for this job. The job fails when trying to run on SAVIO on 3 nodes (Disk out of space error)

**Comment by justinmccrary** [comment]
Interesting.  By the way, the code seems way too simple.  Are you sure it
is correct?

**Comment by rsoni1** [comment]
Can we perhaps check the semantics in the code? As I understood it is Best Bid or Best Offer across al exchanges, with Best Bid defined as max of all bids and Best offer defined as min of all Asks. So this is NBBO across exchanges per a given timestamp in the data. http://www.investopedia.com/terms/n/nbbo.asp

I notice in the post above you've mentioned lowest price per second per exchange. I can make this tweak in the code just need to know the right semantics for NBBO.

**Comment by justinmccrary** [comment]
Yes, but at least in other languages, there needs to be a way of explaining
to the software that olds bids (asks) are valid until updated.  The max is
across the "current" bids (asks), where that might mean a bid (ask) from a
long time ago.  So if the data looked like

ex  time  bid  ask
A 1 22.1 25.2
B 2 22.2 25.1
C 3 22.4 25.2
A 4 22.2 24.9
A 5 22.2 0
C 5 0 0

where we should pretend time is measured in milliseconds, the NBBO should
look like

time BBid BAsk notes_from_justin
1 22.1 25.2 (because A is only exchange offering)
2 22.2 25.1 (because B beats A on both bid and ask)
3 22.4 25.1 (because C beats B on bid, but B still beats A and C on ask)
4 22.4 24.9 (because A now beats B and C on ask, but C is still offering
best bid)
5 22.2 25.1 (because A cancels its ask, so B offers the best ask, and C has
cancelled its bid (and ask), so the best bid is shared between A and B)

Is that what your code produces?

**Comment by rsoni1** [comment]
Yes that is precisely what the code does.

**Comment by rsoni1** [comment]
Aaah.. typed too soon. except for the canceling logic. didn't realize that the 0 is a canceling the ask or the bid. That's a small tweak.

**Comment by rsoni1** [comment]
Would you want me to filter out the bid/asks with bid-size or ask-size = 0? or is that treated as a cancel as well?

**Comment by rsoni1** [comment]
Updated code with the bid/ask canceling logic. These are the elif statements in the processquote function. This code now implements the NBBO semantics as described by Justin above.

**Comment by davclark** [comment]
Shall we close this?

**Comment by rsoni1** [comment]
Yes we can close this. I will make one last edit to the code per some notes Nital had in his conversation with Justin in treating Quote Cancel/Correction flag where A - Valid quote and B - Cancel quote. I'll add these additional checks in here.

**Comment by rsoni1** [comment]
Updated code with the Quote Cancel/Correction flag. Also I've added the zipWithIndex step in order to preserve the original ordering in case of tied timestamps. This final NBBO code will be used for the crossings calculation code.

Justin, please let me know if there are any further conditions that need to be considered for the NBBO calculation. The final code is here https://github.com/berkeley-dsc/dlab-finance/tree/master/nbbo
